/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const appImages = {
  Image1: require('@assets/appimages/Image1.png'),
  Image2: require('@assets/appimages/Image2.png'),
  Image3: require('@assets/appimages/Image3.png'),
  Image4: require('@assets/appimages/Image4.png'),
  Image5: require('@assets/appimages/Image5.png'),
  Image6: require('@assets/appimages/Image6.png'),
  Image7: require('@assets/appimages/Image7.png'),
  Image8: require('@assets/appimages/Image8.png'),
  Right: require('@assets/appimages/Right.png'),
  Back: require('@assets/appimages/Back.png'),
  Search: require('@assets/appimages/Search.png'),
  Setting: require('@assets/appimages/Setting.png'),
  SettingIcon: require('@assets/appimages/SettingIcon.png'),
  RightArrow: require('@assets/appimages/RightArrow.png'),
  T: require('@assets/appimages/T.png'),
  Star: require('@assets/appimages/Star.png'),
  FAQ: require('@assets/appimages/FAQ.png'),
  Inbox: require('@assets/appimages/Inbox.png'),
  Lock: require('@assets/appimages/Lock.png'),
  Condition: require('@assets/appimages/Condition.png'),
  Logout: require('@assets/appimages/Logout.png'),
  Menu: require('@assets/appimages/Menu.png'),
  Google: require('@assets/appimages/Google.png'),
  Apple: require('@assets/appimages/Apple.png'),
  Facebook: require('@assets/appimages/Facebook.png'),
  NBAIcon: require('@assets/appimages/NBAIcon.png'),
  Home: require('@assets/appimages/Home.png'),
  Results: require('@assets/appimages/Results.png'),
  Mic: require('@assets/appimages/Mic.png'),
  Clock: require('@assets/appimages/Clock.png'),
  LeftArrow: require('@assets/appimages/LeftArrow.png'),
  MessageIcon: require('@assets/appimages/MessageIcon.png'),
  SendIcon: require('@assets/appimages/SendIcon.png'),
  SaveIcon: require('@assets/appimages/SaveIcon.png'),
  LeftArrowWhite: require('@assets/appimages/LeftArrowWhite.png'),
  Notification: require('@assets/appimages/Notification.png'),
  NotificationIcon: require('@assets/appimages/NotificationIcon.png'),
  ArrowIcon: require('@assets/appimages/ArrowIcon.png'),
  Forward: require('@assets/appimages/Forward.png'),
  Play: require('@assets/appimages/Play.png'),
  Rewind: require('@assets/appimages/Rewind.png'),
  Next: require('@assets/appimages/Next.png'),
  Pause: require('@assets/appimages/Pause.png'),
};
